version: '3.0'

volumes:
  mongodbvol:

services:
  mongodb:
    container_name: mongodb
    build:
      context: ./a-coders-spring
      dockerfile: Dockerfile-mongo
    image: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodbvol:/data/db
    environment:
      - TZ=Asia/Singapore

  scrapper:
    container_name: scrapper
    build:
      context: ./a-coders-python
      dockerfile: Dockerfile-python
    image: scrapper
    links:
      - mongodb:mongodb
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mongodb
      - DB_NAME=acoders
      - TZ=Asia/Singapore

  spring-app:
    container_name: spring-app
    build:
      context: ./a-coders-spring
      dockerfile: Dockerfile-spring
    image: spring-app
    ports:
      - "8080:8080"
    links:
      - mongodb:mongodb
    environment:
      - DB_HOST=mongodb
      - DB_NAME=acoders
      - TZ=Asia/Singapore

  simulator:
    container_name: simulator
    build:
      context: ./a-coders-trade-simulator
      dockerfile: Dockerfile
    image: simulator
    links:
      - mongodb:mongodb
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=mongodb
      - DB_NAME=acoders
      - TZ=Asia/Singapore
  angular:
    container_name: angular
    build:
      context: ./a-coders-angular
      dockerfile: Dockerfile-angular
    image: angular
    ports:
      - "4200:4200"
    environment:
      - API_URL=spring-app
      - TZ=Asia/Singapore
